version: "3.8"

services:
  # These are the configurations for our Node app
  # When Docker Compose starts this container it will automatically
  # use the Dockerfile in the directory to configure it
  fhir-converter:
    build:
      context: ./
      dockerfile: Dockerfile
    deploy:
      restart_policy:
          condition: on-failure
    environment:
      - NODE_ENV=development
      - ENV_TYPE=development
    ports:
      - "8777:8080"
      - "9277:9229"
    volumes:
      - ./src:/app/src
    extra_hosts:
      - "host.docker.internal:host-gateway"
