name: Reusable Release workflow

on:
  workflow_call: # called by other workflows
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
  workflow_dispatch: # manually executed by a user - should be able to remove this once semver is well mature

# From https://thecodinganalyst.github.io/knowledgebase/Using-Semantic-Release-with-Github-Actions/
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - run: env
        shell: bash
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.14"
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false # bc PAT? https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
      - run: |
          echo "Git ref: $(git rev-parse HEAD)"
        shell: bash
      - name: Install dependencies
        run: npm run install-deps
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pwd
          npx semantic-release
